version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: linkedin_jobs_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: linkedin_jobs

volumes:
  mongo_data:
